"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v$kp6c(&&c)%z*a5tcd65o6wo12f1)3!-&j@e4p%2u9@8p3z16'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    'pwa',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp', 
    'social_django',
]
############################################################聊天室
ASGI_APPLICATION = 'myproject.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
                       ###########################################################



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    

]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  
        # 改過上面
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]





WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用 MySQL 代替 SQLite
        'HOST': '140.131.114.242',             # 資料庫主機地址
        'PORT': '3306',                        # MySQL 的預設端口號
        'USER': '114502',                      # 資料庫使用者名稱
        'PASSWORD': '114502Data@',             # 資料庫密碼
        'NAME': '114-502Data',                # 這裡填入你使用的資料庫名稱
    }
}





# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

TIME_ZONE = 'Asia/Taipei'  # ✅ 設定為台灣時區

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# 如果你有自定義靜態文件目錄，確保它正確
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myapp/static'),
]

# 在生產環境中，也需要設置 STATIC_ROOT 用來收集靜態文件
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# 讓 collectstatic 指定的目錄
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field



# 在這行之後放 Google 登入相關設定
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
SOCIAL_AUTH_FORCE_SIGNUP = False

# Google OAuth2 登入設定
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '26102906571-lh75nv79tt5p1ls92n7mdkd0hq7v5dfc.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['name', 'email', 'picture']

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)



AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # Google 登入
    'django.contrib.auth.backends.ModelBackend',
)


LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = '/'  # 成功登入後的轉址
LOGIN_REDIRECT_URL = '/this_user_profile'  # 登出後的轉址



# 確保在 settings.py 中配置 MEDIA_URL 和 MEDIA_ROOT
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True  #  使用者登入時自動切換綁定帳號



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'pabeng54@gmail.com'               # 你的 Gmail 地址
EMAIL_HOST_PASSWORD = 'owjwkrwqeerfweow'  # 你的「應用程式密碼」，空格去掉



ALLOWED_TAGS = ['a']
ALLOWED_ATTRIBUTES = {
    'a': ['href', 'target', 'rel']
}

#PWA
PWA_APP_NAME = '怪怪走開護您安全'
PWA_APP_DESCRIPTION = "Django as a PWA"
PWA_APP_THEME_COLOR = '#033e6b'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_ICONS = [
    {
        'src': '/static/icons/icon-192x192.png?v=2',
        'sizes': '192x192'
    },
    {
        'src': '/static/icons/icon-512x512.png?v=2',
        'sizes': '512x512'
    }
]