# Generated by Django 4.2.5 on 2025-07-21 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_gmail', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('image_url', models.BinaryField()),
            ],
            options={
                'db_table': 'education_page',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PemapAll',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('poster_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('address', models.CharField(default='尚未提供', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('img_url', models.TextField(blank=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_reviewed', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(default='待審核', max_length=50)),
                ('admin_id', models.IntegerField(default=99999)),
            ],
            options={
                'db_table': 'pemap_all',
            },
        ),
        migrations.CreateModel(
            name='PoliceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct_name', models.TextField()),
                ('zipcode', models.CharField(max_length=3)),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('POINT_X', models.FloatField()),
                ('POINT_Y', models.FloatField()),
            ],
            options={
                'db_table': 'PoliceAddress',
            },
        ),
        migrations.CreateModel(
            name='StoreAll',
            fields=[
                ('st_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('poster_id', models.CharField(blank=True, max_length=255)),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(default='尚未提供', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('business_hours', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(default='pending', max_length=20)),
                ('admin_id', models.IntegerField(default=99999)),
            ],
            options={
                'db_table': 'store_all',
            },
        ),
        migrations.CreateModel(
            name='TaiwanRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=3)),
                ('country_city', models.CharField(max_length=50)),
                ('district_town', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'taiwan_regions',
            },
        ),
        migrations.CreateModel(
            name='ThisUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254)),
                ('default_nickname1', models.CharField(blank=True, max_length=100)),
                ('default_nickname2', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_gmail', models.EmailField(blank=True, max_length=254)),
                ('default_message', models.TextField(blank=True)),
                ('self_intro', models.TextField(blank=True)),
                ('user_images', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
            options={
                'db_table': 'this_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('show_name_option', models.IntegerField(default=3)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
