# Generated by Django 5.1.6 on 2025-03-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_recipe_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
