# Generated by Django 4.2.5 on 2025-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_storeall_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('bgcolor', models.CharField(max_length=20)),
                ('avatar_style', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_interaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10)),
                ('country_city', models.CharField(max_length=50)),
                ('district_town', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pemapall',
            name='poster_gmail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeall',
            name='poster_gmail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policeaddress',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='taiwanregion',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
