# Generated by Django 5.1.6 on 2025-08-01 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chatinteraction_region_pemapall_poster_gmail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thisuserprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 1, 16, 1, 21, 809772)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thisuserprofile',
            name='status_color',
            field=models.CharField(default='#63b3ed', max_length=20),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='user_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
