# Generated by Django 4.2.5 on 2025-05-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiwanRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_city', models.CharField(max_length=50)),
                ('district_town', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'taiwan_regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThisUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254)),
                ('default_nickname1', models.CharField(blank=True, max_length=100)),
                ('default_nickname2', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_gmail', models.EmailField(blank=True, max_length=254)),
                ('default_message', models.TextField(blank=True)),
                ('self_intro', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
    ]
