# Generated by Django 4.2.5 on 2025-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_taiwanregion_thisuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thisuserprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thisuserprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='thisuserprofile',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='default_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='default_nickname1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='default_nickname2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='emergency_contact_gmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='self_intro',
            field=models.TextField(),
        ),
    ]
