# Generated by Django 4.2.5 on 2025-08-06 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_thisuserprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemapWithSubkind',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('subkind', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('img_url', models.TextField(blank=True)),
                ('time_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'pemap_with_subkind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('click_count', models.IntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='區域名稱', max_length=50)),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='點擊聊天室的使用者（未登入為 NULL）', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天室點擊紀錄',
                'verbose_name_plural': '聊天室點擊紀錄',
                'db_table': 'chat_room_clicks',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='區域名稱', max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='留言的使用者', on_delete=django.db.models.deletion.CASCADE, to='myapp.thisuserprofile')),
            ],
            options={
                'verbose_name': '聊天室訊息',
                'verbose_name_plural': '聊天室訊息',
                'db_table': 'chat_messages',
            },
        ),
    ]
