# Generated by Django 4.2.5 on 2025-08-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pemapwithsubkind_chatroom_chatroomclick_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='留言的使用者', on_delete=django.db.models.deletion.CASCADE, to='myapp.thisuserprofile'),
        ),
        migrations.CreateModel(
            name='FavoriteChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='myapp.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_chat_rooms', to='myapp.thisuserprofile')),
            ],
            options={
                'verbose_name': '使用者收藏聊天室',
                'verbose_name_plural': '使用者收藏聊天室',
                'db_table': 'favorite_chat_rooms',
                'unique_together': {('user', 'chat_room')},
            },
        ),
    ]
