# Generated by Django 4.2.5 on 2025-05-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_thisuserprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thisuserprofile',
            name='default_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='default_nickname1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='default_nickname2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='emergency_contact_gmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='self_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='thisuserprofile',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
