# Generated by Django 4.2.5 on 2025-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_thisuserprofile_default_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('分局名稱', models.CharField(max_length=100)),
                ('郵遞區號', models.CharField(max_length=10)),
                ('地址', models.CharField(max_length=200)),
                ('電話', models.CharField(max_length=50)),
                ('POINT_X', models.FloatField()),
                ('POINT_Y', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='taiwanregion',
            options={},
        ),
    ]
