# Generated by Django 4.2.5 on 2025-08-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_chatmessage_user_favoritechatroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
