# Generated by Django 4.2.5 on 2025-09-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_chatmessage_options_chatmessage_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='myapp.chatmessage'),
        ),
        migrations.CreateModel(
            name='StoreAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_content', models.TextField(blank=True, null=True)),
                ('ad_radius', models.IntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(db_column='st_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.storeall')),
            ],
            options={
                'db_table': 'store_ad',
            },
        ),
    ]
