# Generated by Django 4.2.5 on 2025-05-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_policeaddress_alter_taiwanregion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiwanregion',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taiwanregion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='taiwanregion',
            table=None,
        ),
    ]
