# Generated by Django 4.2.5 on 2025-05-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_taiwanregion_zipcode_alter_taiwanregion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thisuserprofile',
            table='this_user_profile',
        ),
    ]
