# Generated by Django 4.2.5 on 2025-05-28 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_alter_thisuserprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PemapAll',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('poster_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_reviewed', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(default='待處理', max_length=50)),
            ],
            options={
                'db_table': 'pemap_all',
            },
        ),
        migrations.AddField(
            model_name='thisuserprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='this_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
