# Generated by Django 5.1.6 on 2025-09-03 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_storead_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', '貼文'), ('comment', '留言'), ('reply', '回覆')], db_index=True, max_length=20)),
                ('comment_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reply_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reason', models.CharField(choices=[('spam', '垃圾訊息/廣告'), ('abuse', '辱罵/騷擾'), ('hate', '仇恨/歧視'), ('violence', '暴力/威脅'), ('nudity', '裸露/色情'), ('illegal', '違法內容'), ('doxxing', '人身資訊外流'), ('misinfo', '錯誤資訊'), ('other', '其他')], db_index=True, default='other', max_length=32)),
                ('details', models.TextField(blank=True, default='')),
                ('snapshot_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', '待審'), ('action_taken', '已處置'), ('rejected', '已駁回')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='myapp.chatinteraction')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '檢舉',
                'verbose_name_plural': '檢舉',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='myapp_abuse_status_67ce52_idx'), models.Index(fields=['reason'], name='myapp_abuse_reason_f3a771_idx'), models.Index(fields=['created_at'], name='myapp_abuse_created_5611c2_idx'), models.Index(fields=['comment_id'], name='myapp_abuse_comment_d4df46_idx'), models.Index(fields=['reply_id'], name='myapp_abuse_reply_i_0cde8f_idx')],
            },
        ),
    ]
