# Generated by Django 5.1.6 on 2025-09-09 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_abusereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAdImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_ad_image',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='abusereport',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': '檢舉', 'verbose_name_plural': '檢舉'},
        ),
        migrations.AlterModelOptions(
            name='storeall',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('report', '檢舉'), ('system', '系統'), ('like', '按讚'), ('comment', '留言')], default='system', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='myapp_notif_recipie_a39187_idx'), models.Index(fields=['recipient', '-created_at'], name='myapp_notif_recipie_057d22_idx')],
            },
        ),
    ]
