# Generated by Django 4.2.5 on 2025-05-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_incident_pemapall_thisuserprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thisuserprofile',
            name='user',
        ),
    ]
