# Generated by Django 5.1.6 on 2025-07-06 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_thisuserprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAll',
            fields=[
                ('st_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('poster_id', models.CharField(blank=True, max_length=255)),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('business_hours', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'store_all',
            },
        ),
        migrations.AlterField(
            model_name='pemapall',
            name='img_url',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pemapall',
            name='kind',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pemapall',
            name='poster_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pemapall',
            name='review_status',
            field=models.CharField(default='待審核', max_length=50),
        ),
        migrations.AlterField(
            model_name='pemapall',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
